## Copyright 2024 Dean Hall, all rights reserved.  See LICENSE.txt for details.
#[
Metagenerator converts peripheral, register and field declarations into
symbols and procs that enable programmer-friendly, type-safe access
to Arm Cortex-M special function registers, their fields and enum values.
The declarations come from silicon vendors' SVD files that are
converted by minisvd2nim.

These templates and macros are not used by the minisvd2nim program.
Instead, the code generated by minisvd2nim calls these templates and macros.
This allows the programmer to change the final form of the Nim source
by editing this file and not changing or recompiling the minisvd2nim binary.

Two ARM assembly instructions, BFI and UBFX, are used in setField and
getField when compiling for ARM targets.  These instructions perform bit
field insert and extract operations in a single instruction.  The emitted
assembly syntax is for GCC inline assembly.  Here is a reference:
  https://gcc.gnu.org/onlinedocs/gcc/Using-Assembly-Language-with-C.html

Note: In this file, the term "mask" is defined as a word having its bits set
to ones in the positions of interest.  So, a field mask has ones set in the
field's bit positions.
]#
#!fmt: off

import std/[macros, tables, volatile]

type
  RegType = uint32
  # Encode the address into the Peripheral, RegAddr and *Val types so that
  # the address is available to the tail of the call chain (usually a write)
  Peripheral[Taddr: static RegType] = distinct RegType
  RegAddr[Taddr: static RegType] = distinct RegType
  RegVal[Taddr: static RegType] = distinct RegType
  FldVal[Taddr: static RegType] = distinct RegType

var
  # Store some attributes that are set within declare* templates
  # for use at compile time outside of their declare* templates
  regReadAccess {.compileTime.} = initTable[RegType, bool]()
  regWriteAccess {.compileTime.} = initTable[RegType, bool]()
  regIsDimensioned {.compileTime.} = initTable[RegType, bool]()
  regDim {.compileTime.} = initTable[RegType, RegType]()
  regDimIncrement {.compileTime.} = initTable[RegType, RegType]()

proc read*[Taddr: static RegType](_: RegAddr[Taddr], index: static int = 0): RegVal[Taddr] {.inline.} =
  ## Returns the value loaded from the index's offset from the register.
  ## Implements `PER.REG.read()`
  when not regReadAccess[Taddr]:
    {.error: "Attempted read from a register without read access.".}
  when index > 0 and not regIsDimensioned[Taddr]:
    {.error: "Attempted dimensioned access to a non-dimensioned register.".}
  when index >= regDim[Taddr] and regDim[Taddr] != 0:
    {.error: "Attempted write to a register index beyond its limit.".}
  const a: RegType = Taddr + index.RegType * regDimIncrement[Taddr]
  const r = cast[ptr RegVal[Taddr]](a)
  volatileLoad(r)

proc write*[Taddr: static RegType](_: RegAddr[Taddr], value: RegVal[Taddr] | RegType) {.inline.} =
  ## Writes the value to the register.
  ## Implements `PER.REG.write(value)`
  when not regWriteAccess[Taddr]:
    {.error: "Attempted write to a register without write access.".}
  const p = cast[ptr RegType](Taddr)
  volatileStore(p, value.RegType)

template declareDevice*(deviceName: untyped, svdFileVersion: static string, description: static string, ): untyped =
  # Device details tuple
  const device* {.inject.} = (name: astToStr(deviceName), svdFileVer: svdFileVersion, desc: description)

template declareCpu*(cpuName: untyped, revision: static string, endian: static string, mpuPresent: static bool, fpuPresent: static bool, nvicPrioBits: static int, vendorSysTick: static int): untyped =
  # CPU details tuple
  const cpu* {.inject.} = (name: astToStr(cpuName), rev: revision, endianness: endian, mpuAvail: mpuPresent, fpuAvail: fpuPresent, nvicPriorityBits: nvicPrioBits, vndrSysTick: vendorSysTick != 0)

template declarePeripheral*(peripheralName: untyped, baseAddress: static uint32, peripheralDesc: static string): untyped =
  const `peripheralName`* {.inject.} = Peripheral[baseAddress.RegType](baseAddress.RegType)

template declareInterrupt*(peripheralName: untyped, interruptName: untyped, interruptValue: static int, interruptDesc: static string, ): untyped =
  const `irq _ interruptName`* {.inject.} = interruptValue # `interruptDesc`

template declareRegister*(peripheralName: untyped, registerName: untyped, addressOffset: static uint32,
                          dim: static int = 0, dimIncrement: static int = 0,
                          readAccess: static bool, writeAccess: static bool, registerDesc: static string): untyped =
  const isDimensioned = dim != 0 and dimIncrement != 0
  const regAddr: RegType = peripheralName.uint32 + addressOffset
  const `peripheralName _ registerName` {.inject.} = regAddr # used by declareField and declareFieldEnum
  # Special support for fields of dimensioned registers: encode the register name and address into the type
  # so that the field procs can act on the indexed register using its address.
  type `peripheralName _ registerName _ RegAddr`*[Taddr: static RegType] = distinct RegAddr[Taddr]
  type `peripheralName _ registerName _ RegVal`*[Taddr: static RegType] = distinct RegVal[Taddr]

  converter toRegAddr*[Taddr: static RegType](x: `peripheralName _ registerName _ RegAddr`[Taddr]): RegAddr[Taddr] {.inline.} =
    cast[RegAddr[Taddr]](x)

  converter toRegVal*[Taddr: static RegType](x: `peripheralName _ registerName _ RegVal`[Taddr]): RegVal[Taddr] {.inline.} =
    cast[RegVal[Taddr]](x)

  proc read*[Taddr: static RegType](_: `peripheralName _ registerName _ RegAddr`[Taddr], index: static int = 0): `peripheralName _ registerName _ RegVal`[Taddr] {.inline.} =
    when not regReadAccess[Taddr]:
      {.error: "Attempted read from a register without read access.".}
    when index > 0 and not regIsDimensioned[Taddr]:
      {.error: "Attempted dimensioned access to a non-dimensioned register.".}
    when index >= regDim[Taddr] and regDim[Taddr] != 0:
      {.error: "Attempted write to a register index beyond its limit.".}
    const a: RegType = Taddr + index.RegType * regDimIncrement[Taddr]
    const r = cast[ptr RegType](a)
    `peripheralName _ registerName _ RegVal`[Taddr](volatileLoad(r))

  static:
    # Set attributes of the declared register
    regDim[regAddr] = dim
    regDimIncrement[regAddr] = dimIncrement.RegType
    regIsDimensioned[regAddr] = dim != 0 and dimIncrement != 0
    regReadAccess[regAddr] = readAccess
    regWriteAccess[regAddr] = writeAccess
    # Dimensioned regiser
    for i in 1.RegType ..< dim:
      let dimAddr = peripheralName.uint32 + addressOffset + dimIncrement.RegType * i
      regDim[dimAddr] = dim
      regDimIncrement[dimAddr] = dimIncrement.RegType
      regIsDimensioned[dimAddr] = false
      regReadAccess[dimAddr] = readAccess
      regWriteAccess[dimAddr] = writeAccess

  func registerName*(_: Peripheral[peripheralName.RegType], index: static int = 0): auto {.inline.} =
    ## Returns the dimensioned register's address as a RegAddr[Taddr]
    ## Implements `PER.REG(1)`
    when index > 0 and not isDimensioned:
      {.error: "Attempted dimensioned access of non-dimensioned register."}
    when index >= dim and dim > 0:
      {.error: "Attempted dimensioned register access beyond its limit.".}
    const a = RegType(peripheralName.uint32 + addressOffset + index.uint32 * dimIncrement.uint32)
    cast[`peripheralName _ registerName _ RegAddr`[a]](a)

# TODO: add support for non-static index
#  func registerName*(p: Peripheral[peripheralName.uint32], index: uint = 0'u): auto {.inline.} =
#    ## Returns the dimensioned register's address as a RegAddr[Taddr]
#    ## Non-static index, compared to the previous func
#    ## Implements `PER.REG(n)`
#    when not isDimensioned:
#      assert index == 0, "Attempted dimensioned access of non-dimensioned register."
#    assert index >= 0 and index < dim, "Attempted dimensioned access of non-dimensioned register."
#    let a = peripheralName.uint32 + addressOffset + index * dimIncrement.uint32
#    RegAddr[a](a.uint32) # can't eval at compile time; FLAW: RegAddr[] type parameter must be static

func getField[Taddr: static RegType](regVal: RegVal[Taddr], bitOffset: static uint8, bitWidth: static uint8): FldVal[Taddr] {.inline.} =
  ## Returns the bit field masked and down shifted to the zero'th bit
  when bitWidth == 0: {.error: "bitWidth must be greater than zero".}
  when (bitOffset + bitWidth) > 32'u8: {.error: "bit field must not exceed register size in bits".}
  when defined(arm):
    {.emit: ["asm (\"ubfx %0, %1, %2, %3\"\n\t: \"=r\" (", result, ")\n\t: \"r\" (", regVal, "), \"n\" (", bitOffset, "), \"n\" (", bitWidth, "));\n"].}
  else: # for desktop testing
    const fldMask = 0xFFFFFFFF'u32 shr (32 - bitWidth)
    FldVal[Taddr]((regVal.uint32 shr bitOffset) and fldMask)

func getField[Taddr: static RegType](regVal: RegVal[Taddr], bitOffset: uint8, bitWidth: static uint8): FldVal[Taddr] {.inline.} =
  ## Returns the bit field masked and down shifted to the zero'th bit
  ## Non-static bitOffset, compared to the previous func
  when bitWidth == 0: {.error: "bitWidth must be greater than zero".}
  assert (bitOffset + bitWidth) < 32'u8, "bit field must not exceed register size in bits"
  when defined(arm):
    {.emit: ["asm (\"ubfx %0, %1, %2, %3\"\n\t: \"=r\" (", result, ")\n\t: \"r\" (", regVal, "), \"n\" (", bitOffset, "), \"n\" (", bitWidth, "));\n"].}
  else: # for desktop testing
    const fldMask = 0xFFFFFFFF'u32 shr (32 - bitWidth)
    FldVal[Taddr]((regVal.uint32 shr bitOffset) and fldMask)

func setField[Taddr: static RegType](fldVal: FldVal[Taddr], value: RegType, bitOffset: static uint8, bitWidth: static uint8): FldVal[Taddr] {.inline.} =
  ## Returns `fldVal` with `value` shifted and inserted into the given bit offset and width.
  ## No bits outside of the bit offset and width are changed.
  when bitWidth == 0: {.error: "bitWidth must be greater than zero".}
  when (bitOffset + bitWidth) > 32: {.error: "bit field must not exceed register size in bits".}
  when defined(arm):
    result = fldVal
    {.emit: ["asm (\"bfi %0, %1, %2, %3\"\n\t: \"+r\" (", result, ")\n\t: \"r\" (", value, "), \"n\" (", bitOffset, "), \"n\" (", bitWidth, "));\n"].}
  else: # for desktop testing
    const fldMask = 0xFFFFFFFF'u32 shr (32 - bitWidth) shl bitOffset
    let r = fldVal.uint32 and not fldMask
    FldVal[Taddr](r or ((value.uint32 shl bitOffset) and fldMask))

func setField[Taddr: static RegType](fldVal: FldVal[Taddr], value: RegType, bitOffset: uint8, bitWidth: static uint8): FldVal[Taddr] {.inline.} =
  ## Returns `fldVal` with `value` shifted and inserted into the given bit offset and width.
  ## No bits outside of the bit offset and width are changed.
  ## Non-static bitOffset, compared to the previous func
  when bitWidth == 0: {.error: "bitWidth must be greater than zero".}
  assert (bitOffset + bitWidth) < 32, "bit field must not exceed register size in bits"
  when defined(arm):
    result = fldVal
    {.emit: ["asm (\"bfi %0, %1, %2, %3\"\n\t: \"+r\" (", result, ")\n\t: \"r\" (", value, "), \"n\" (", bitOffset, "), \"n\" (", bitWidth, "));\n"].}
  else: # for desktop testing
    let fldMask = 0xFFFFFFFF'u32 shr (32 - bitWidth) shl bitOffset
    let r: uint32 = fldVal.uint32 and not fldMask
    FldVal[Taddr](r or ((value.uint32 shl bitOffset) and fldMask))

proc write*[Taddr: static RegType](value: FldVal[Taddr]) {.inline.} =
  ## Writes the value to the register (volatile store).
  ## Implements the write part of `PER.REG.FLD(v1).write`
  ## NOTE: write access is already enforced at compile time
  ## by the fieldName procs that produce FldVal.
  const regAddr = cast[ptr FldVal[Taddr]](Taddr)
  volatileStore(regAddr, value)

template declareField*(peripheralName: untyped, registerName: untyped, fieldName: untyped,
                       bitOffset: static uint8, bitWidth: static uint8, dim: static int = 0, dimIncrement: static int = 0,
                       readAccess: static bool, writeAccess: static bool, fieldDesc: static string): untyped =
  const isDimensioned = dim != 0 and dimIncrement != 0
  const regAddr: RegType = `peripheralName _ registerName`

  when isDimensioned:
    proc fieldName*[Taddr: static RegType](_: `peripheralName _ registerName _ RegAddr`[Taddr], index: static uint32, value: RegType) {.inline.} =
      ## Overwrites the register's field's bits with the value.
      ## Overwrites the bits outside the field with zeroes.
      ## Implements the FLD part of `PER.REG.FLD(1, value)`
      when not writeAccess:
        {.error: "Attempted write to a field without write access.".}
      when index >= dim and dim > 0:
        {.error: "Attempted dimensioned register access beyond its limit.".}
      const initVal = FldVal[Taddr](0'u32)
      const bitOff = index.uint8 * dimIncrement
      let v = setField[Taddr](initVal, value, bitOff, bitWidth)
      const regAddr = cast[ptr RegType](Taddr)
      volatileStore(regAddr, v.RegType)

    proc fieldName*[Taddr: static RegType](_: `peripheralName _ registerName _ RegAddr`[Taddr], index: uint32, value: RegType) {.inline.} =
      ## Non-static index, compared to the previous proc
      ## Overwrites the register's field's bits with the value (runtime index).
      ## Overwrites the bits outside the field with zeroes.
      ## Implements the FLD part of `PER.REG.FLD(n, value)`
      when not writeAccess:
        {.error: "Attempted write to a field without write access.".}
      assert index >= 0 and index < dim, "Attempted dimensioned register access beyond its limit."
      const initVal = FldVal[Taddr](0'u32)
      let bitOff = uint8(index) * dimIncrement.uint8
      let v = setField[Taddr](initVal, value, bitOff, bitWidth)
      const regPtr = cast[ptr RegType](Taddr)
      volatileStore(regPtr, v.RegType)

    proc fieldName*[Taddr: static RegType](regVal: `peripheralName _ registerName _ RegVal`[Taddr], index: static uint32): FldVal[Taddr] {.inline.} =
      ## Reads the field from the register value (static index)
      ## Implements the FLD part of `PER.REG.read().FLD(1)
      when not readAccess:
        {.error: "Attempted read from a field without read access.".}
      when index >= dim and dim > 0:
        {.error: "Attempted dimensioned register access beyond its limit.".}
      const bitOff = index.uint8 * dimIncrement
      getField[Taddr](regVal, bitOff, bitWidth)

    proc fieldName*[Taddr: static RegType](regVal: `peripheralName _ registerName _ RegVal`[Taddr], index: uint32): FldVal[Taddr] {.inline.} =
      ## Non-static index, compared to the previous proc
      ## Reads the field from the register value (runtime index).
      ## Implements the FLD part of `PER.REG.read().FLD(n)`
      when not readAccess:
        {.error: "Attempted read from a field without read access.".}
      let bitOff = uint8(index) * dimIncrement.uint8
      getField[Taddr](regVal, bitOff, bitWidth)

    proc fieldName*[Taddr: static RegType](inVal: `peripheralName _ registerName _ RegVal`[Taddr] | FldVal[Taddr], index: static uint32, value: RegType): FldVal[Taddr] {.inline.} =
      ## Rmw's the field's bits in the register with `value`.
      ## Returns the FldVal[Taddr] type to allow chaining of more field modifications.
      ## Implements the FLD part of `PER.REG.read().FLD(idx, value)`
      when not writeAccess:
        {.error: "Attempted write to a field without write access.".}
      when index >= dim:
        {.error: "Attempted write to a field index beyond its limit.".}
      let fldVal = cast[FldVal[Taddr]](inVal)
      const bitOff = index.uint8 * dimIncrement
      setField[Taddr](fldVal, value, bitOff, bitWidth)

  else: # not dimensioned
    proc fieldName*[Taddr: static RegType](_: `peripheralName _ registerName _ RegAddr`[Taddr], value: RegType) {.inline.} =
      ## Overwrites the register's field's bits with the value.
      ## Overwrites the bits outside the field with zeroes.
      ## Implements the FLD part of `PER.REG.FLD(1, value)`
      when not writeAccess:
        {.error: "Attempted write to a field without write access.".}
      const initVal = FldVal[Taddr](0'u32)
      let v = setField[Taddr](initVal, value, bitOffset, bitWidth)
      const regAddr = cast[ptr RegType](Taddr)
      volatileStore(regAddr, v.RegType)

    proc fieldName*[Taddr: static RegType](regVal: `peripheralName _ registerName _ RegVal`[Taddr]): FldVal[Taddr] {.inline.} =
      ## Reads the field from the register value
      ## Implements the FLD part of `PER.REG.read().FLD(1)
      when not readAccess:
        {.error: "Attempted read from a field without read access.".}
      getField[Taddr](regVal, bitOffset, bitWidth)

    proc fieldName*[Taddr: static RegType](inVal: `peripheralName _ registerName _ RegVal`[Taddr] | FldVal[Taddr], value: RegType): FldVal[Taddr] {.inline.} =
      ## Rmw's the field's bits in the register with `value`.
      ## Returns the FldVal[Taddr] type to allow chaining of more field modifications.
      ## Implements the FLD part of `PER.REG.read().FLD(idx, value)`
      when not writeAccess:
        {.error: "Attempted write to a field without write access.".}
      let fldVal = cast[FldVal[Taddr]](inVal)
      setField[Taddr](fldVal, value, bitOffset, bitWidth)

macro declareEnum(enumType: untyped, enumPairsStmtList: untyped) {.inject.} =
  ## Declares a Nim enumerator with the given type that is bound to a specific register.
  ## The enum names and values are from the SVD file.
  enumPairsStmtList.expectKind(nnkStmtList)
  var fields: seq[NimNode]
  for asgnNode in enumPairsStmtList:
    asgnNode.expectKind(nnkAsgn)
    var node = newNimNode(nnkEnumFieldDef)
    node.add(asgnNode[0])
    node.add(asgnNode[1])
    fields.add(node)
  newEnum(name = enumType, fields = fields, public = true, pure = true)  # TODO: are we sure we want pure?

macro declareFieldEnum*(peripheralName: untyped, registerName: untyped, fieldName: untyped,
                        bitOffset: static int, bitWidth: static int,
                        readAccess: static bool, writeAccess: static bool, values: untyped) {.inject.} =
  ## Declares an enum type for a register field and overloaded procs for type-safe access.
  ## When writeAccess: generates a field= overload accepting the enum type.
  ## When readAccess and writeAccess: generates RMW chain overloads accepting the enum type.
  let enumType = ident(peripheralName.strVal & '_' & registerName.strVal & '_' & fieldName.strVal & "_enum")
  let brandedAddrType = ident(peripheralName.strVal & '_' & registerName.strVal & "_RegAddr")
  let brandedAddrTypeInst = nnkBracketExpr.newTree(brandedAddrType, ident("Taddr"))
  let brandedValType = ident(peripheralName.strVal & '_' & registerName.strVal & "_RegVal")
  let brandedValTypeInst = nnkBracketExpr.newTree(brandedValType, ident("Taddr"))
  result = newStmtList()
  result.add(quote do:
    declareEnum(`enumType`, `values`))
  if writeAccess:
    result.add(quote do:
      proc `fieldName`*[Taddr: static RegType](regAddr: `brandedAddrTypeInst`, value: `enumType`) {.inline.} =
        `fieldName`(regAddr, value.uint32))
  if readAccess and writeAccess:
    result.add(quote do:
      proc `fieldName`*[Taddr: static RegType](regVal: `brandedValTypeInst`, value: `enumType`): FldVal[Taddr] {.inline.} =
        `fieldName`(regVal, value.uint32)
      proc `fieldName`*[Taddr: static RegType](chainVal: FldVal[Taddr], value: `enumType`): FldVal[Taddr] {.inline.} =
        `fieldName`(chainVal, value.uint32))
